<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pmfaq"
 *
 * Auto generated by Extension Builder 2015-08-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'FAQ',
	'description' => 'Bindet ein Modul zur Anzeige von häufig gestellten Fragen (FAQ) auf der Seite ein.',
	'category' => 'plugin',
	'author' => 'Julian Stock',
	'author_email' => 'stock@parrot-media.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
